/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 32
#define LARGE_STATE_COUNT 4
#define SYMBOL_COUNT 39
#define ALIAS_COUNT 0
#define TOKEN_COUNT 22
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 4
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_Title_COLON = 1,
  aux_sym_title_page_line_token1 = 2,
  anon_sym_POUND = 3,
  anon_sym_EQ = 4,
  anon_sym_INT_DOT = 5,
  anon_sym_EXT_DOT = 6,
  anon_sym_EST_DOT = 7,
  anon_sym_INT_DOT_SLASHEXT_DOT = 8,
  anon_sym_DOT = 9,
  anon_sym_GT = 10,
  anon_sym_LT = 11,
  sym_page_break = 12,
  sym_separator = 13,
  anon_sym_TILDE = 14,
  anon_sym_LPAREN = 15,
  anon_sym_RPAREN = 16,
  anon_sym_LBRACK_LBRACK = 17,
  anon_sym_RBRACK_RBRACK = 18,
  anon_sym_SLASH_STAR = 19,
  anon_sym_STAR_SLASH = 20,
  sym_word = 21,
  sym_document = 22,
  sym__line = 23,
  sym_title_page_line = 24,
  sym_section = 25,
  sym_synopsis = 26,
  sym_scene_heading = 27,
  sym_scene_location = 28,
  sym_transition = 29,
  sym_centered = 30,
  sym_lyrics = 31,
  sym_character_line = 32,
  sym_parenthetical = 33,
  sym_dialogue = 34,
  sym_note_inline = 35,
  sym_boneyard = 36,
  sym_action = 37,
  aux_sym_document_repeat1 = 38,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_Title_COLON] = "Title:",
  [aux_sym_title_page_line_token1] = "title_page_line_token1",
  [anon_sym_POUND] = "#",
  [anon_sym_EQ] = "=",
  [anon_sym_INT_DOT] = "INT.",
  [anon_sym_EXT_DOT] = "EXT.",
  [anon_sym_EST_DOT] = "EST.",
  [anon_sym_INT_DOT_SLASHEXT_DOT] = "INT./EXT.",
  [anon_sym_DOT] = ".",
  [anon_sym_GT] = ">",
  [anon_sym_LT] = "<",
  [sym_page_break] = "page_break",
  [sym_separator] = "separator",
  [anon_sym_TILDE] = "~",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_LBRACK_LBRACK] = "[[",
  [anon_sym_RBRACK_RBRACK] = "]]",
  [anon_sym_SLASH_STAR] = "/*",
  [anon_sym_STAR_SLASH] = "*/",
  [sym_word] = "word",
  [sym_document] = "document",
  [sym__line] = "_line",
  [sym_title_page_line] = "title_page_line",
  [sym_section] = "section",
  [sym_synopsis] = "synopsis",
  [sym_scene_heading] = "scene_heading",
  [sym_scene_location] = "scene_location",
  [sym_transition] = "transition",
  [sym_centered] = "centered",
  [sym_lyrics] = "lyrics",
  [sym_character_line] = "character_line",
  [sym_parenthetical] = "parenthetical",
  [sym_dialogue] = "dialogue",
  [sym_note_inline] = "note_inline",
  [sym_boneyard] = "boneyard",
  [sym_action] = "action",
  [aux_sym_document_repeat1] = "document_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_Title_COLON] = anon_sym_Title_COLON,
  [aux_sym_title_page_line_token1] = aux_sym_title_page_line_token1,
  [anon_sym_POUND] = anon_sym_POUND,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_INT_DOT] = anon_sym_INT_DOT,
  [anon_sym_EXT_DOT] = anon_sym_EXT_DOT,
  [anon_sym_EST_DOT] = anon_sym_EST_DOT,
  [anon_sym_INT_DOT_SLASHEXT_DOT] = anon_sym_INT_DOT_SLASHEXT_DOT,
  [anon_sym_DOT] = anon_sym_DOT,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_LT] = anon_sym_LT,
  [sym_page_break] = sym_page_break,
  [sym_separator] = sym_separator,
  [anon_sym_TILDE] = anon_sym_TILDE,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_LBRACK_LBRACK] = anon_sym_LBRACK_LBRACK,
  [anon_sym_RBRACK_RBRACK] = anon_sym_RBRACK_RBRACK,
  [anon_sym_SLASH_STAR] = anon_sym_SLASH_STAR,
  [anon_sym_STAR_SLASH] = anon_sym_STAR_SLASH,
  [sym_word] = sym_word,
  [sym_document] = sym_document,
  [sym__line] = sym__line,
  [sym_title_page_line] = sym_title_page_line,
  [sym_section] = sym_section,
  [sym_synopsis] = sym_synopsis,
  [sym_scene_heading] = sym_scene_heading,
  [sym_scene_location] = sym_scene_location,
  [sym_transition] = sym_transition,
  [sym_centered] = sym_centered,
  [sym_lyrics] = sym_lyrics,
  [sym_character_line] = sym_character_line,
  [sym_parenthetical] = sym_parenthetical,
  [sym_dialogue] = sym_dialogue,
  [sym_note_inline] = sym_note_inline,
  [sym_boneyard] = sym_boneyard,
  [sym_action] = sym_action,
  [aux_sym_document_repeat1] = aux_sym_document_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_Title_COLON] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_title_page_line_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_POUND] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_INT_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EXT_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EST_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_INT_DOT_SLASHEXT_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [sym_page_break] = {
    .visible = true,
    .named = true,
  },
  [sym_separator] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_TILDE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR_SLASH] = {
    .visible = true,
    .named = false,
  },
  [sym_word] = {
    .visible = true,
    .named = true,
  },
  [sym_document] = {
    .visible = true,
    .named = true,
  },
  [sym__line] = {
    .visible = false,
    .named = true,
  },
  [sym_title_page_line] = {
    .visible = true,
    .named = true,
  },
  [sym_section] = {
    .visible = true,
    .named = true,
  },
  [sym_synopsis] = {
    .visible = true,
    .named = true,
  },
  [sym_scene_heading] = {
    .visible = true,
    .named = true,
  },
  [sym_scene_location] = {
    .visible = true,
    .named = true,
  },
  [sym_transition] = {
    .visible = true,
    .named = true,
  },
  [sym_centered] = {
    .visible = true,
    .named = true,
  },
  [sym_lyrics] = {
    .visible = true,
    .named = true,
  },
  [sym_character_line] = {
    .visible = true,
    .named = true,
  },
  [sym_parenthetical] = {
    .visible = true,
    .named = true,
  },
  [sym_dialogue] = {
    .visible = true,
    .named = true,
  },
  [sym_note_inline] = {
    .visible = true,
    .named = true,
  },
  [sym_boneyard] = {
    .visible = true,
    .named = true,
  },
  [sym_action] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_document_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(28);
      ADVANCE_MAP(
        '#', 33,
        '(', 57,
        ')', 59,
        '*', 8,
        '-', 3,
        '.', 45,
        '/', 1,
        '<', 49,
        '=', 35,
        '>', 47,
        'E', 13,
        'I', 12,
        'T', 22,
        '[', 19,
        ']', 20,
        '~', 55,
      );
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == '*') ADVANCE(63);
      END_STATE();
    case 2:
      if (lookahead == '-') ADVANCE(53);
      END_STATE();
    case 3:
      if (lookahead == '-') ADVANCE(2);
      END_STATE();
    case 4:
      if (lookahead == '.') ADVANCE(41);
      END_STATE();
    case 5:
      if (lookahead == '.') ADVANCE(39);
      END_STATE();
    case 6:
      if (lookahead == '.') ADVANCE(37);
      END_STATE();
    case 7:
      if (lookahead == '.') ADVANCE(43);
      END_STATE();
    case 8:
      if (lookahead == '/') ADVANCE(65);
      END_STATE();
    case 9:
      if (lookahead == ':') ADVANCE(29);
      END_STATE();
    case 10:
      if (lookahead == '=') ADVANCE(51);
      END_STATE();
    case 11:
      if (lookahead == 'E') ADVANCE(18);
      END_STATE();
    case 12:
      if (lookahead == 'N') ADVANCE(16);
      END_STATE();
    case 13:
      if (lookahead == 'S') ADVANCE(14);
      if (lookahead == 'X') ADVANCE(15);
      END_STATE();
    case 14:
      if (lookahead == 'T') ADVANCE(4);
      END_STATE();
    case 15:
      if (lookahead == 'T') ADVANCE(5);
      END_STATE();
    case 16:
      if (lookahead == 'T') ADVANCE(6);
      END_STATE();
    case 17:
      if (lookahead == 'T') ADVANCE(7);
      END_STATE();
    case 18:
      if (lookahead == 'X') ADVANCE(17);
      END_STATE();
    case 19:
      if (lookahead == '[') ADVANCE(60);
      END_STATE();
    case 20:
      if (lookahead == ']') ADVANCE(62);
      END_STATE();
    case 21:
      if (lookahead == 'e') ADVANCE(9);
      END_STATE();
    case 22:
      if (lookahead == 'i') ADVANCE(24);
      END_STATE();
    case 23:
      if (lookahead == 'l') ADVANCE(21);
      END_STATE();
    case 24:
      if (lookahead == 't') ADVANCE(23);
      END_STATE();
    case 25:
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(90);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n') ADVANCE(91);
      END_STATE();
    case 26:
      if (eof) ADVANCE(28);
      ADVANCE_MAP(
        '#', 34,
        '(', 58,
        '-', 70,
        '.', 46,
        '/', 68,
        '<', 50,
        '=', 36,
        '>', 48,
        'E', 79,
        'I', 78,
        'T', 87,
        '[', 85,
        '~', 56,
        '\t', 66,
        ' ', 66,
      );
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n') ADVANCE(91);
      END_STATE();
    case 27:
      if (eof) ADVANCE(28);
      ADVANCE_MAP(
        '#', 34,
        '(', 58,
        '-', 70,
        '.', 46,
        '/', 68,
        '=', 36,
        '>', 48,
        'E', 79,
        'I', 78,
        'T', 87,
        '[', 85,
        '~', 56,
        '\t', 67,
        ' ', 67,
      );
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n') ADVANCE(91);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_Title_COLON);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_Title_COLON);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(91);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(aux_sym_title_page_line_token1);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(31);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n') ADVANCE(32);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(aux_sym_title_page_line_token1);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(32);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_POUND);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_POUND);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(91);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_EQ);
      if (lookahead == '=') ADVANCE(10);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_EQ);
      if (lookahead == '=') ADVANCE(76);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(91);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_INT_DOT);
      if (lookahead == '/') ADVANCE(11);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_INT_DOT);
      if (lookahead == '/') ADVANCE(77);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(91);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_EXT_DOT);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_EXT_DOT);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(91);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_EST_DOT);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_EST_DOT);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(91);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_INT_DOT_SLASHEXT_DOT);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_INT_DOT_SLASHEXT_DOT);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(91);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_DOT);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(91);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(anon_sym_GT);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(anon_sym_GT);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(91);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(anon_sym_LT);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(anon_sym_LT);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(91);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(sym_page_break);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(sym_page_break);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(91);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(sym_separator);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(sym_separator);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(91);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(anon_sym_TILDE);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(anon_sym_TILDE);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(91);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(91);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(anon_sym_LBRACK_LBRACK);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(anon_sym_LBRACK_LBRACK);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(91);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(anon_sym_RBRACK_RBRACK);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(anon_sym_SLASH_STAR);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(anon_sym_SLASH_STAR);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(91);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(anon_sym_STAR_SLASH);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(sym_word);
      ADVANCE_MAP(
        '#', 34,
        '(', 58,
        '-', 70,
        '.', 46,
        '/', 68,
        '<', 50,
        '=', 36,
        '>', 48,
        'E', 79,
        'I', 78,
        'T', 87,
        '[', 85,
        '~', 56,
        '\t', 66,
        ' ', 66,
      );
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n') ADVANCE(91);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(sym_word);
      ADVANCE_MAP(
        '#', 34,
        '(', 58,
        '-', 70,
        '.', 46,
        '/', 68,
        '=', 36,
        '>', 48,
        'E', 79,
        'I', 78,
        'T', 87,
        '[', 85,
        '~', 56,
        '\t', 67,
        ' ', 67,
      );
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n') ADVANCE(91);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(sym_word);
      if (lookahead == '*') ADVANCE(64);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(91);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(sym_word);
      if (lookahead == '-') ADVANCE(54);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(91);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(sym_word);
      if (lookahead == '-') ADVANCE(69);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(91);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(sym_word);
      if (lookahead == '.') ADVANCE(42);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(91);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(sym_word);
      if (lookahead == '.') ADVANCE(40);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(91);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(sym_word);
      if (lookahead == '.') ADVANCE(38);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(91);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(sym_word);
      if (lookahead == '.') ADVANCE(44);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(91);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(sym_word);
      if (lookahead == ':') ADVANCE(30);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(91);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(sym_word);
      if (lookahead == '=') ADVANCE(52);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(91);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(sym_word);
      if (lookahead == 'E') ADVANCE(84);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(91);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(sym_word);
      if (lookahead == 'N') ADVANCE(82);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(91);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(sym_word);
      if (lookahead == 'S') ADVANCE(80);
      if (lookahead == 'X') ADVANCE(81);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(91);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(sym_word);
      if (lookahead == 'T') ADVANCE(71);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(91);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(sym_word);
      if (lookahead == 'T') ADVANCE(72);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(91);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(sym_word);
      if (lookahead == 'T') ADVANCE(73);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(91);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(sym_word);
      if (lookahead == 'T') ADVANCE(74);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(91);
      END_STATE();
    case 84:
      ACCEPT_TOKEN(sym_word);
      if (lookahead == 'X') ADVANCE(83);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(91);
      END_STATE();
    case 85:
      ACCEPT_TOKEN(sym_word);
      if (lookahead == '[') ADVANCE(61);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(91);
      END_STATE();
    case 86:
      ACCEPT_TOKEN(sym_word);
      if (lookahead == 'e') ADVANCE(75);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(91);
      END_STATE();
    case 87:
      ACCEPT_TOKEN(sym_word);
      if (lookahead == 'i') ADVANCE(89);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(91);
      END_STATE();
    case 88:
      ACCEPT_TOKEN(sym_word);
      if (lookahead == 'l') ADVANCE(86);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(91);
      END_STATE();
    case 89:
      ACCEPT_TOKEN(sym_word);
      if (lookahead == 't') ADVANCE(88);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(91);
      END_STATE();
    case 90:
      ACCEPT_TOKEN(sym_word);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(90);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n') ADVANCE(91);
      END_STATE();
    case 91:
      ACCEPT_TOKEN(sym_word);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(91);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 27},
  [2] = {.lex_state = 27},
  [3] = {.lex_state = 27},
  [4] = {.lex_state = 26},
  [5] = {.lex_state = 27},
  [6] = {.lex_state = 27},
  [7] = {.lex_state = 27},
  [8] = {.lex_state = 27},
  [9] = {.lex_state = 27},
  [10] = {.lex_state = 27},
  [11] = {.lex_state = 27},
  [12] = {.lex_state = 27},
  [13] = {.lex_state = 27},
  [14] = {.lex_state = 27},
  [15] = {.lex_state = 27},
  [16] = {.lex_state = 27},
  [17] = {.lex_state = 25},
  [18] = {.lex_state = 25},
  [19] = {.lex_state = 31},
  [20] = {.lex_state = 25},
  [21] = {.lex_state = 25},
  [22] = {.lex_state = 25},
  [23] = {.lex_state = 25},
  [24] = {.lex_state = 25},
  [25] = {.lex_state = 31},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 25},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_Title_COLON] = ACTIONS(1),
    [anon_sym_POUND] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_INT_DOT] = ACTIONS(1),
    [anon_sym_EXT_DOT] = ACTIONS(1),
    [anon_sym_EST_DOT] = ACTIONS(1),
    [anon_sym_INT_DOT_SLASHEXT_DOT] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [sym_page_break] = ACTIONS(1),
    [sym_separator] = ACTIONS(1),
    [anon_sym_TILDE] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_LBRACK_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK_RBRACK] = ACTIONS(1),
    [anon_sym_SLASH_STAR] = ACTIONS(1),
    [anon_sym_STAR_SLASH] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_document] = STATE(26),
    [sym__line] = STATE(2),
    [sym_title_page_line] = STATE(2),
    [sym_section] = STATE(2),
    [sym_synopsis] = STATE(2),
    [sym_scene_heading] = STATE(2),
    [sym_transition] = STATE(2),
    [sym_centered] = STATE(2),
    [sym_lyrics] = STATE(2),
    [sym_character_line] = STATE(2),
    [sym_parenthetical] = STATE(2),
    [sym_dialogue] = STATE(2),
    [sym_note_inline] = STATE(2),
    [sym_boneyard] = STATE(2),
    [sym_action] = STATE(2),
    [aux_sym_document_repeat1] = STATE(2),
    [anon_sym_Title_COLON] = ACTIONS(3),
    [anon_sym_POUND] = ACTIONS(5),
    [anon_sym_EQ] = ACTIONS(7),
    [anon_sym_INT_DOT] = ACTIONS(9),
    [anon_sym_EXT_DOT] = ACTIONS(9),
    [anon_sym_EST_DOT] = ACTIONS(9),
    [anon_sym_INT_DOT_SLASHEXT_DOT] = ACTIONS(9),
    [anon_sym_DOT] = ACTIONS(9),
    [anon_sym_GT] = ACTIONS(11),
    [sym_page_break] = ACTIONS(13),
    [sym_separator] = ACTIONS(13),
    [anon_sym_TILDE] = ACTIONS(15),
    [anon_sym_LPAREN] = ACTIONS(17),
    [anon_sym_LBRACK_LBRACK] = ACTIONS(19),
    [anon_sym_SLASH_STAR] = ACTIONS(21),
    [sym_word] = ACTIONS(23),
  },
  [STATE(2)] = {
    [sym__line] = STATE(3),
    [sym_title_page_line] = STATE(3),
    [sym_section] = STATE(3),
    [sym_synopsis] = STATE(3),
    [sym_scene_heading] = STATE(3),
    [sym_transition] = STATE(3),
    [sym_centered] = STATE(3),
    [sym_lyrics] = STATE(3),
    [sym_character_line] = STATE(3),
    [sym_parenthetical] = STATE(3),
    [sym_dialogue] = STATE(3),
    [sym_note_inline] = STATE(3),
    [sym_boneyard] = STATE(3),
    [sym_action] = STATE(3),
    [aux_sym_document_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(25),
    [anon_sym_Title_COLON] = ACTIONS(3),
    [anon_sym_POUND] = ACTIONS(5),
    [anon_sym_EQ] = ACTIONS(7),
    [anon_sym_INT_DOT] = ACTIONS(9),
    [anon_sym_EXT_DOT] = ACTIONS(9),
    [anon_sym_EST_DOT] = ACTIONS(9),
    [anon_sym_INT_DOT_SLASHEXT_DOT] = ACTIONS(9),
    [anon_sym_DOT] = ACTIONS(9),
    [anon_sym_GT] = ACTIONS(11),
    [sym_page_break] = ACTIONS(27),
    [sym_separator] = ACTIONS(27),
    [anon_sym_TILDE] = ACTIONS(15),
    [anon_sym_LPAREN] = ACTIONS(17),
    [anon_sym_LBRACK_LBRACK] = ACTIONS(19),
    [anon_sym_SLASH_STAR] = ACTIONS(21),
    [sym_word] = ACTIONS(23),
  },
  [STATE(3)] = {
    [sym__line] = STATE(3),
    [sym_title_page_line] = STATE(3),
    [sym_section] = STATE(3),
    [sym_synopsis] = STATE(3),
    [sym_scene_heading] = STATE(3),
    [sym_transition] = STATE(3),
    [sym_centered] = STATE(3),
    [sym_lyrics] = STATE(3),
    [sym_character_line] = STATE(3),
    [sym_parenthetical] = STATE(3),
    [sym_dialogue] = STATE(3),
    [sym_note_inline] = STATE(3),
    [sym_boneyard] = STATE(3),
    [sym_action] = STATE(3),
    [aux_sym_document_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(29),
    [anon_sym_Title_COLON] = ACTIONS(31),
    [anon_sym_POUND] = ACTIONS(34),
    [anon_sym_EQ] = ACTIONS(37),
    [anon_sym_INT_DOT] = ACTIONS(40),
    [anon_sym_EXT_DOT] = ACTIONS(40),
    [anon_sym_EST_DOT] = ACTIONS(40),
    [anon_sym_INT_DOT_SLASHEXT_DOT] = ACTIONS(40),
    [anon_sym_DOT] = ACTIONS(40),
    [anon_sym_GT] = ACTIONS(43),
    [sym_page_break] = ACTIONS(46),
    [sym_separator] = ACTIONS(46),
    [anon_sym_TILDE] = ACTIONS(49),
    [anon_sym_LPAREN] = ACTIONS(52),
    [anon_sym_LBRACK_LBRACK] = ACTIONS(55),
    [anon_sym_SLASH_STAR] = ACTIONS(58),
    [sym_word] = ACTIONS(61),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 3,
    ACTIONS(64), 1,
      ts_builtin_sym_end,
    ACTIONS(68), 1,
      anon_sym_LT,
    ACTIONS(66), 16,
      anon_sym_Title_COLON,
      anon_sym_POUND,
      anon_sym_EQ,
      anon_sym_INT_DOT,
      anon_sym_EXT_DOT,
      anon_sym_EST_DOT,
      anon_sym_INT_DOT_SLASHEXT_DOT,
      anon_sym_DOT,
      anon_sym_GT,
      sym_page_break,
      sym_separator,
      anon_sym_TILDE,
      anon_sym_LPAREN,
      anon_sym_LBRACK_LBRACK,
      anon_sym_SLASH_STAR,
      sym_word,
  [25] = 3,
    ACTIONS(70), 1,
      ts_builtin_sym_end,
    ACTIONS(78), 1,
      anon_sym_LPAREN,
    ACTIONS(74), 15,
      anon_sym_Title_COLON,
      anon_sym_POUND,
      anon_sym_EQ,
      anon_sym_INT_DOT,
      anon_sym_EXT_DOT,
      anon_sym_EST_DOT,
      anon_sym_INT_DOT_SLASHEXT_DOT,
      anon_sym_DOT,
      anon_sym_GT,
      sym_page_break,
      sym_separator,
      anon_sym_TILDE,
      anon_sym_LBRACK_LBRACK,
      anon_sym_SLASH_STAR,
      sym_word,
  [49] = 2,
    ACTIONS(83), 1,
      ts_builtin_sym_end,
    ACTIONS(85), 16,
      anon_sym_Title_COLON,
      anon_sym_POUND,
      anon_sym_EQ,
      anon_sym_INT_DOT,
      anon_sym_EXT_DOT,
      anon_sym_EST_DOT,
      anon_sym_INT_DOT_SLASHEXT_DOT,
      anon_sym_DOT,
      anon_sym_GT,
      sym_page_break,
      sym_separator,
      anon_sym_TILDE,
      anon_sym_LPAREN,
      anon_sym_LBRACK_LBRACK,
      anon_sym_SLASH_STAR,
      sym_word,
  [71] = 2,
    ACTIONS(87), 1,
      ts_builtin_sym_end,
    ACTIONS(89), 16,
      anon_sym_Title_COLON,
      anon_sym_POUND,
      anon_sym_EQ,
      anon_sym_INT_DOT,
      anon_sym_EXT_DOT,
      anon_sym_EST_DOT,
      anon_sym_INT_DOT_SLASHEXT_DOT,
      anon_sym_DOT,
      anon_sym_GT,
      sym_page_break,
      sym_separator,
      anon_sym_TILDE,
      anon_sym_LPAREN,
      anon_sym_LBRACK_LBRACK,
      anon_sym_SLASH_STAR,
      sym_word,
  [93] = 2,
    ACTIONS(91), 1,
      ts_builtin_sym_end,
    ACTIONS(93), 16,
      anon_sym_Title_COLON,
      anon_sym_POUND,
      anon_sym_EQ,
      anon_sym_INT_DOT,
      anon_sym_EXT_DOT,
      anon_sym_EST_DOT,
      anon_sym_INT_DOT_SLASHEXT_DOT,
      anon_sym_DOT,
      anon_sym_GT,
      sym_page_break,
      sym_separator,
      anon_sym_TILDE,
      anon_sym_LPAREN,
      anon_sym_LBRACK_LBRACK,
      anon_sym_SLASH_STAR,
      sym_word,
  [115] = 2,
    ACTIONS(95), 1,
      ts_builtin_sym_end,
    ACTIONS(97), 16,
      anon_sym_Title_COLON,
      anon_sym_POUND,
      anon_sym_EQ,
      anon_sym_INT_DOT,
      anon_sym_EXT_DOT,
      anon_sym_EST_DOT,
      anon_sym_INT_DOT_SLASHEXT_DOT,
      anon_sym_DOT,
      anon_sym_GT,
      sym_page_break,
      sym_separator,
      anon_sym_TILDE,
      anon_sym_LPAREN,
      anon_sym_LBRACK_LBRACK,
      anon_sym_SLASH_STAR,
      sym_word,
  [137] = 2,
    ACTIONS(99), 1,
      ts_builtin_sym_end,
    ACTIONS(101), 16,
      anon_sym_Title_COLON,
      anon_sym_POUND,
      anon_sym_EQ,
      anon_sym_INT_DOT,
      anon_sym_EXT_DOT,
      anon_sym_EST_DOT,
      anon_sym_INT_DOT_SLASHEXT_DOT,
      anon_sym_DOT,
      anon_sym_GT,
      sym_page_break,
      sym_separator,
      anon_sym_TILDE,
      anon_sym_LPAREN,
      anon_sym_LBRACK_LBRACK,
      anon_sym_SLASH_STAR,
      sym_word,
  [159] = 2,
    ACTIONS(103), 1,
      ts_builtin_sym_end,
    ACTIONS(105), 16,
      anon_sym_Title_COLON,
      anon_sym_POUND,
      anon_sym_EQ,
      anon_sym_INT_DOT,
      anon_sym_EXT_DOT,
      anon_sym_EST_DOT,
      anon_sym_INT_DOT_SLASHEXT_DOT,
      anon_sym_DOT,
      anon_sym_GT,
      sym_page_break,
      sym_separator,
      anon_sym_TILDE,
      anon_sym_LPAREN,
      anon_sym_LBRACK_LBRACK,
      anon_sym_SLASH_STAR,
      sym_word,
  [181] = 2,
    ACTIONS(107), 1,
      ts_builtin_sym_end,
    ACTIONS(109), 16,
      anon_sym_Title_COLON,
      anon_sym_POUND,
      anon_sym_EQ,
      anon_sym_INT_DOT,
      anon_sym_EXT_DOT,
      anon_sym_EST_DOT,
      anon_sym_INT_DOT_SLASHEXT_DOT,
      anon_sym_DOT,
      anon_sym_GT,
      sym_page_break,
      sym_separator,
      anon_sym_TILDE,
      anon_sym_LPAREN,
      anon_sym_LBRACK_LBRACK,
      anon_sym_SLASH_STAR,
      sym_word,
  [203] = 2,
    ACTIONS(111), 1,
      ts_builtin_sym_end,
    ACTIONS(113), 16,
      anon_sym_Title_COLON,
      anon_sym_POUND,
      anon_sym_EQ,
      anon_sym_INT_DOT,
      anon_sym_EXT_DOT,
      anon_sym_EST_DOT,
      anon_sym_INT_DOT_SLASHEXT_DOT,
      anon_sym_DOT,
      anon_sym_GT,
      sym_page_break,
      sym_separator,
      anon_sym_TILDE,
      anon_sym_LPAREN,
      anon_sym_LBRACK_LBRACK,
      anon_sym_SLASH_STAR,
      sym_word,
  [225] = 2,
    ACTIONS(115), 1,
      ts_builtin_sym_end,
    ACTIONS(117), 16,
      anon_sym_Title_COLON,
      anon_sym_POUND,
      anon_sym_EQ,
      anon_sym_INT_DOT,
      anon_sym_EXT_DOT,
      anon_sym_EST_DOT,
      anon_sym_INT_DOT_SLASHEXT_DOT,
      anon_sym_DOT,
      anon_sym_GT,
      sym_page_break,
      sym_separator,
      anon_sym_TILDE,
      anon_sym_LPAREN,
      anon_sym_LBRACK_LBRACK,
      anon_sym_SLASH_STAR,
      sym_word,
  [247] = 2,
    ACTIONS(119), 1,
      ts_builtin_sym_end,
    ACTIONS(121), 16,
      anon_sym_Title_COLON,
      anon_sym_POUND,
      anon_sym_EQ,
      anon_sym_INT_DOT,
      anon_sym_EXT_DOT,
      anon_sym_EST_DOT,
      anon_sym_INT_DOT_SLASHEXT_DOT,
      anon_sym_DOT,
      anon_sym_GT,
      sym_page_break,
      sym_separator,
      anon_sym_TILDE,
      anon_sym_LPAREN,
      anon_sym_LBRACK_LBRACK,
      anon_sym_SLASH_STAR,
      sym_word,
  [269] = 2,
    ACTIONS(123), 1,
      ts_builtin_sym_end,
    ACTIONS(125), 16,
      anon_sym_Title_COLON,
      anon_sym_POUND,
      anon_sym_EQ,
      anon_sym_INT_DOT,
      anon_sym_EXT_DOT,
      anon_sym_EST_DOT,
      anon_sym_INT_DOT_SLASHEXT_DOT,
      anon_sym_DOT,
      anon_sym_GT,
      sym_page_break,
      sym_separator,
      anon_sym_TILDE,
      anon_sym_LPAREN,
      anon_sym_LBRACK_LBRACK,
      anon_sym_SLASH_STAR,
      sym_word,
  [291] = 2,
    ACTIONS(127), 1,
      sym_word,
    STATE(13), 1,
      sym_scene_location,
  [298] = 1,
    ACTIONS(129), 1,
      sym_word,
  [302] = 1,
    ACTIONS(131), 1,
      aux_sym_title_page_line_token1,
  [306] = 1,
    ACTIONS(133), 1,
      sym_word,
  [310] = 1,
    ACTIONS(135), 1,
      sym_word,
  [314] = 1,
    ACTIONS(137), 1,
      sym_word,
  [318] = 1,
    ACTIONS(139), 1,
      sym_word,
  [322] = 1,
    ACTIONS(141), 1,
      sym_word,
  [326] = 1,
    ACTIONS(143), 1,
      aux_sym_title_page_line_token1,
  [330] = 1,
    ACTIONS(145), 1,
      ts_builtin_sym_end,
  [334] = 1,
    ACTIONS(147), 1,
      anon_sym_STAR_SLASH,
  [338] = 1,
    ACTIONS(149), 1,
      sym_word,
  [342] = 1,
    ACTIONS(151), 1,
      anon_sym_RBRACK_RBRACK,
  [346] = 1,
    ACTIONS(153), 1,
      anon_sym_RPAREN,
  [350] = 1,
    ACTIONS(155), 1,
      anon_sym_RPAREN,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(4)] = 0,
  [SMALL_STATE(5)] = 25,
  [SMALL_STATE(6)] = 49,
  [SMALL_STATE(7)] = 71,
  [SMALL_STATE(8)] = 93,
  [SMALL_STATE(9)] = 115,
  [SMALL_STATE(10)] = 137,
  [SMALL_STATE(11)] = 159,
  [SMALL_STATE(12)] = 181,
  [SMALL_STATE(13)] = 203,
  [SMALL_STATE(14)] = 225,
  [SMALL_STATE(15)] = 247,
  [SMALL_STATE(16)] = 269,
  [SMALL_STATE(17)] = 291,
  [SMALL_STATE(18)] = 298,
  [SMALL_STATE(19)] = 302,
  [SMALL_STATE(20)] = 306,
  [SMALL_STATE(21)] = 310,
  [SMALL_STATE(22)] = 314,
  [SMALL_STATE(23)] = 318,
  [SMALL_STATE(24)] = 322,
  [SMALL_STATE(25)] = 326,
  [SMALL_STATE(26)] = 330,
  [SMALL_STATE(27)] = 334,
  [SMALL_STATE(28)] = 338,
  [SMALL_STATE(29)] = 342,
  [SMALL_STATE(30)] = 346,
  [SMALL_STATE(31)] = 350,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = false}}, SHIFT(19),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(18),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(25),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(17),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(20),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(2),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(21),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(22),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(23),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(24),
  [23] = {.entry = {.count = 1, .reusable = false}}, SHIFT(5),
  [25] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 1, 0, 0),
  [27] = {.entry = {.count = 1, .reusable = false}}, SHIFT(3),
  [29] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0),
  [31] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(19),
  [34] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(18),
  [37] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(25),
  [40] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(17),
  [43] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(20),
  [46] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [49] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(21),
  [52] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(22),
  [55] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(23),
  [58] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(24),
  [61] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(5),
  [64] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_transition, 2, 0, 0),
  [66] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_transition, 2, 0, 0),
  [68] = {.entry = {.count = 1, .reusable = false}}, SHIFT(14),
  [70] = {.entry = {.count = 3, .reusable = true}}, REDUCE(sym_character_line, 1, 0, 0), REDUCE(sym_dialogue, 1, 0, 0), REDUCE(sym_action, 1, 0, 0),
  [74] = {.entry = {.count = 3, .reusable = false}}, REDUCE(sym_character_line, 1, 0, 0), REDUCE(sym_dialogue, 1, 0, 0), REDUCE(sym_action, 1, 0, 0),
  [78] = {.entry = {.count = 4, .reusable = false}}, REDUCE(sym_character_line, 1, 0, 0), REDUCE(sym_dialogue, 1, 0, 0), REDUCE(sym_action, 1, 0, 0), SHIFT(28),
  [83] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_title_page_line, 2, 0, 0),
  [85] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_title_page_line, 2, 0, 0),
  [87] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_section, 2, 0, 0),
  [89] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_section, 2, 0, 0),
  [91] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_scene_location, 1, 0, 0),
  [93] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_scene_location, 1, 0, 0),
  [95] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_synopsis, 2, 0, 0),
  [97] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_synopsis, 2, 0, 0),
  [99] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_lyrics, 2, 0, 0),
  [101] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_lyrics, 2, 0, 0),
  [103] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parenthetical, 3, 0, 0),
  [105] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_parenthetical, 3, 0, 0),
  [107] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_note_inline, 3, 0, 0),
  [109] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_note_inline, 3, 0, 0),
  [111] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_scene_heading, 2, 0, 0),
  [113] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_scene_heading, 2, 0, 0),
  [115] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_centered, 3, 0, 0),
  [117] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_centered, 3, 0, 0),
  [119] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_boneyard, 3, 0, 0),
  [121] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_boneyard, 3, 0, 0),
  [123] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_character_line, 4, 0, 0),
  [125] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_character_line, 4, 0, 0),
  [127] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [129] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [131] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [133] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [135] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [137] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [139] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [141] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [143] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [145] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [147] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [149] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [151] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [153] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [155] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_fountain(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
